# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class CtezSwapStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    cashPool: str
    consumerEntrypoint: str
    lastOracleUpdate: str
    lqtAddress: str
    lqtTotal: str
    metadata: Dict[str, str]
    pendingPoolUpdates: str
    tokenAddress: str
    tokenPool: str
