# generated by datamodel-codegen:
#   filename:  ovens_value.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class OvensValue(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    ctez_outstanding: str
    tez_balance: str
