# generated by datamodel-codegen:
#   filename:  ovens_key.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class OvensKey(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    owner: str
