# generated by datamodel-codegen:
#   filename:  cfmm_price.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CfmmPriceParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    nat_0: str
    nat_1: str
