# generated by datamodel-codegen:
#   filename:  liquidate.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class Handle(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    owner: str


class LiquidateParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    handle: Handle
    quantity: str
    to: str
