# generated by datamodel-codegen:
#   filename:  mint_or_burn.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class MintOrBurnParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    quantity: str
