# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    spender: str


class Allowance(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: str


class TokenMetadata(BaseModel):
    class Config:
        extra = Extra.forbid

    token_id: str
    token_info: Dict[str, str]


class CtezMainStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    allowances: List[Allowance]
    metadata: Dict[str, str]
    token_metadata: Dict[str, TokenMetadata]
    tokens: Dict[str, str]
    total_supply: str
